spring.datasource.url=jdbc:mysql://localhost:3306/oltre
spring.datasource.username=oltre
spring.datasource.password=oltre
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG